services:
  maven:
    image: maven:3.8.6-jdk-8
    user: "$DEFAULT_DOCKER_USER"
    working_dir: /usr/src/maven
    volumes:
      - ./:/usr/src/maven
      - ~/.m2:/var/maven/.m2
      - ../.git:/usr/src/.git:ro
    environment:
      MAVEN_CONFIG: /var/maven/.m2
      GIT_DIR: /usr/src/.git

  node:
    image: opendigitaleducation/node:16-alpine-pnpm
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - ~/.npm:/.npm
      - ../recette:/home/node/recette
  k6:
    image: grafana/k6:master
    volumes:
      - ./src/test/js:/home/k6/src
    environment:
      ROOT_URL: http://172.17.0.1:8090
      DATA_ROOT_PATH: /home/k6/data
      DURATION: 61s
      VUS: 100
      ADMC_LOGIN: tom.mate
      ADMC_PASSWORD: password
